# Generated by Django 4.1.5 on 2023-02-11 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('change_status_user', 'Can change the status user')]},
        ),
    ]
