# Generated by Django 4.1.5 on 2023-01-27 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=60, verbose_name='периодичность')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Тема письма')),
                ('text', models.TextField(verbose_name='Тело письма')),
                ('addressee', models.ManyToManyField(to='mailing.client', verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='Sending_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Status_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.frequency')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.status_settings')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
        migrations.CreateModel(
            name='Send_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(verbose_name='Время рассылки')),
                ('server_response', models.CharField(blank=True, max_length=100, verbose_name='Ответ сервера')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.message')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.sending_status')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытка рассылки',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mailing.settings', verbose_name='Настройки'),
        ),
    ]
